username: '[ Welcome Back, XXXX ]'
outOfSyncPlayingSong: 4
resyncSongUrl: 20
AlternateTopButtonValue: Album
AlternateBottomButtonValue: Artist
discordID: '835023222562095124'
albumORsong: album
websocketName:
state: '-'
details: ''
specificTime: 'Y'
loadLastURL: https://music.youtube.com/watch?list=LM&v=y4OrzvAtTHU
