websocketName:
username: '[ Welcome Back, XXXX ]'
discordID: '835023222562095124'
resyncSongUrl: 10
outOfSyncPlayingSong: 4
delayBeforeLunchingDiscord: 10
AlternateTopButtonValue: Album
AlternateBottomButtonValue: Artist
state: '-'
details: ''
specificTime: 'Y'
albumORsong: album
loadLastURL: https://music.youtube.com/watch?v=y4OrzvAtTHU&list=LM&t=78
