version: 2.1

executors:
  win-executor:
    machine:
      image: 'windows-server-2919-vs2019:stable'

jobs:
  build:
    executor: win-executor
    steps:
      - checkout
      - run:
          name: Set up Node.js
          command: |
            choco install nodejs --version 19.9.0
            refreshenv
      - run:
          name: Install dependencies
          command: |
            npm install 
      - run:
          name: Run start-ci script
          command: |
            npm run start-ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master