version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Check Node.js installation
          command: |
            node -v || echo "Node.js is not installed."
      - run:
          name: Setup Node.js
          command: |
            choco install nodejs.install --version 19.9.0 -y
            refreshenv
      - run:
          name: Install dependencies
          command: |
            cd YTM-OP
            npm install 
      - run:
          name: Run start-ci script
          command: |
            cd YTM-OP
            npm run start-ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master