version: 2.1

jobs:
  build:
    machine:
      image: windows-2019

    steps:
      - checkout

      # Install Node.js
      - run:
          name: Install Node.js
          command: |
            choco install nodejs
            RefreshEnv

      # Install npm packages
      - run:
          name: Install npm packages
          command: npm install

      # Run your start-ci script
      - run:
          name: Start CI
          command: npm run start-ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
