version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/FennBoii/YTM-OP/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  install-npm:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
               - run: choco install wget -y
                - run:
                  command: wget https://nodejs.org/dist/v16.17.0/node-v16.17.0-x86.msi -P C:\Users\circleci\Downloads\
                  shell: cmd.exe
                - run: MsiExec.exe /i C:\Users\circleci\Downloads\node-v16.17.0-x86.msi /qn
                - run: 
                    command: |
                        Start-Process powershell -verb runAs -Args "-start GeneralProfile"
                        nvm install 16.17.0
                        nvm use 16.17.0

workflows:
  my-custom-workflow:
    jobs:
      - install-npm