version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  example-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: npm install --save-dev electron

workflows:
  example-workflow:
    jobs:
      - example-job