version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: false 
          node-version: '20.0.0' 

workflows:
    example-workflow:
      jobs:
        - node/test:
            pkg-manager: npm 
            resource_class: large 
            test-results-for: other 
            run-command: start 