version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
         node-version: '20.0.0'
      - run: apt-get install libnss3 && apt-get update && apt-get upgrade && git clone https://github.com/FennBoii/YTM-OP && cd YTM-OP && npm install puppeteer && ls -la && npm install electron-nightly && npm run start

workflows:
  example-workflow:
    jobs:
      - example-job

# EXTRA VARS
#       - run: npm install
#       - run: npm install --save-dev electron
#       - run: npm run start
#       - node/install:
#          install-yarn: false 
#          node-version: '20.0.0'