# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Hope this works?

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: mkdir "C:\Program Files\YTM-OP" && cd "C:\Program Files\YTM-OP" && type nul > config.js
    - run: echo module.exports = {^>^>"SiteName": "FennBoii",^>^>"GivenNameToken": "4787bb1adad3530f01f72869356668b294284a83",^>^>"RandomToken": "2Td2VIC96F",^>^>"username": "[ Welcome Back, FennBoii ]",^>^>"outOfSyncPlayingSong": 3,^>^>"resyncSongUrl": 6000^>^>} > "C:\Program Files\YTM-OP\config.js"
    - run: npm run start && exit
